
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.adler2]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.6.18"
criteria = "safe-to-run"

[[exemptions.anstyle]]
version = "1.0.10"
criteria = "safe-to-run"

[[exemptions.anstyle-parse]]
version = "0.2.6"
criteria = "safe-to-run"

[[exemptions.anstyle-query]]
version = "1.1.2"
criteria = "safe-to-run"

[[exemptions.anstyle-wincon]]
version = "3.0.7"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.75"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.9.1"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.38"
criteria = "safe-to-run"

[[exemptions.clap_builder]]
version = "4.5.38"
criteria = "safe-to-run"

[[exemptions.clap_derive]]
version = "4.5.32"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "0.7.4"
criteria = "safe-to-run"

[[exemptions.colorchoice]]
version = "1.0.3"
criteria = "safe-to-run"

[[exemptions.crc]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.crc-catalog]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.env_filter]]
version = "0.1.3"
criteria = "safe-to-run"

[[exemptions.env_logger]]
version = "0.11.8"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.31.1"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.is_terminal_polyfill]]
version = "1.70.1"
criteria = "safe-to-run"

[[exemptions.jiff]]
version = "0.2.13"
criteria = "safe-to-run"

[[exemptions.jiff-static]]
version = "0.2.13"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.172"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.27"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.num-derive]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-run"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.11.0"
criteria = "safe-to-run"

[[exemptions.portable-atomic-util]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.95"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.40"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.2.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rpassword]]
version = "7.4.0"
criteria = "safe-to-run"

[[exemptions.rtoolbox]]
version = "0.0.3"
criteria = "safe-to-run"

[[exemptions.rustc-demangle]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.219"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.219"
criteria = "safe-to-run"

[[exemptions.socket2]]
version = "0.5.9"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.11.1"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.101"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.45.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.uuid]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.14.2+wasi-0.2.4"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen-rt]]
version = "0.39.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.25"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.25"
criteria = "safe-to-deploy"
